// DataFrame playground: animates traces produced by `DataFrame --trace`.
//
// Recipes load a trace generated by the C++ binary (web/traces/*.json).
// Pipelines you edit in the browser run through engine.js, a port of the same
// code that tools/verify-port.mjs checks against the binary.

import { runPipeline, parsePipeline } from './engine.js';

const $ = (s, el = document) => el.querySelector(s);
const h = (tag, cls, text) => {
  const e = document.createElement(tag);
  if (cls) e.className = cls;
  if (text != null) e.textContent = text;
  return e;
};
const SVGNS = 'http://www.w3.org/2000/svg';
const svg = (tag, attrs = {}) => {
  const e = document.createElementNS(SVGNS, tag);
  for (const [k, v] of Object.entries(attrs)) e.setAttribute(k, v);
  return e;
};
let ROW = 24;
const HEAD = 30;
const EASE = 'cubic-bezier(.2,.8,.2,1)';
const CANCEL = Symbol('cancel');

// ------------------------------------------------------------- op table --
const ICONS = {
  load: '<path d="M12 4v10m-4-4 4 4 4-4M5 17v2h14v-2"/>',
  filter: '<path d="M4 5h16l-6 7v6l-4 2v-8z"/>',
  select: '<rect x="4" y="4" width="4.5" height="16" rx="1"/><rect x="10" y="4" width="4.5" height="16" rx="1"/><path d="M17 8h3M17 12h3M17 16h3"/>',
  sort: '<path d="M8 4v16m-4-4 4 4 4-4M16 20V4m-4 4 4-4 4 4"/>',
  head: '<path d="M4 6h16M4 10h16M4 14h7"/><path d="M4 18h16" stroke-dasharray="2 3"/>',
  groupby: '<rect x="3" y="4" width="7" height="7" rx="1.5"/><rect x="14" y="4" width="7" height="7" rx="1.5"/><rect x="8.5" y="14" width="7" height="7" rx="1.5"/>',
  join: '<circle cx="9" cy="12" r="5"/><circle cx="15" cy="12" r="5"/>',
  describe: '<path d="M4 20V10m5 10V5m5 15v-7m5 7V8"/>',
};
const OPS = ['load', 'filter', 'select', 'sort', 'head', 'groupby', 'join', 'describe'];
const icon = (op) => `<svg viewBox="0 0 24 24">${ICONS[op] || ICONS.load}</svg>`;
const opColor = (op) => `var(--op-${OPS.includes(op) ? op : 'load'})`;
const gColor = (i) => `var(--g${i % 8})`;

const EXPLAIN = {
  load: 'readCSVFile() parses the header, infers numeric vs text columns and stores each column as one contiguous vector<double>. Text becomes dictionary codes.',
  filter: 'filter() walks row_indices_ and keeps the positions where the predicate holds. It returns a new view: no column data is copied.',
  select: 'select() only rewrites column_indices_. Rows and storage are untouched.',
  sort: 'sort() stable-sorts a copy of row_indices_ by the column values. The frame itself never moves.',
  head: 'head(n) truncates row_indices_ to the first n entries.',
  groupby: 'groupby() hashes the key into unordered_map<double, vector<size_t>>, sorts the keys, then reduces each bucket into a new DataFrame.',
  join: 'join() builds a hash table on the right side, then probes it with each left row in order. Output is a new DataFrame.',
  describe: 'describe() gathers each numeric column of the view, then computes count, mean, sample std, min, quartiles (linear interpolation) and max.',
};

// ---------------------------------------------------------------- state --
const state = {
  doc: null,
  dataset: null,
  recipe: null,
  files: {},
  trace: null,
  source: 'cpp',
  pipeline: '',
  index: -1,
  playing: false,
  speed: 1,
  scene: null,
  frames: new Map(),
};

// --------------------------------------------------------------- format --
function fmt(v) {
  if (typeof v === 'string') return v;
  if (v == null || Number.isNaN(v)) return '–';
  if (Number.isInteger(v)) return String(v);
  const a = Math.abs(v);
  const d = a >= 1000 ? 1 : a >= 100 ? 2 : 3;
  return String(parseFloat(v.toFixed(d)));
}

function measure(col, values) {
  let max = col.name.length + (col.kind === 'cat' ? 4 : 4);
  for (const v of values) max = Math.max(max, fmt(v).length);
  return Math.round(Math.min(190, Math.max(66, max * 7.3 + 24)));
}

// ------------------------------------------------------- scene context --
class Ctx {
  constructor() {
    this.anims = [];
    this.timers = [];
    this.cancelled = false;
  }
  anim(el, frames, o = {}) {
    const a = el.animate(frames, {
      duration: (o.duration ?? 400) / state.speed,
      delay: (o.delay ?? 0) / state.speed,
      easing: o.easing ?? EASE,
      fill: o.fill ?? 'backwards',
    });
    this.anims.push(a);
    return a;
  }
  wait(ms) {
    return new Promise((res, rej) => {
      if (this.cancelled) return rej(CANCEL);
      const t = setTimeout(() => (this.cancelled ? rej(CANCEL) : res()), ms / state.speed);
      this.timers.push([t, rej]);
    });
  }
  async all(list) {
    await Promise.all(list.map((a) => a.finished.catch(() => {})));
    if (this.cancelled) throw CANCEL;
  }
  tween(ms, fn, delay = 0) {
    return new Promise((res) => {
      const start = performance.now() + delay / state.speed;
      const dur = ms / state.speed;
      const tick = (now) => {
        if (this.cancelled) return res();
        const p = Math.min(1, Math.max(0, (now - start) / dur));
        fn(1 - Math.pow(1 - p, 3));
        if (p < 1) requestAnimationFrame(tick);
        else res();
      };
      requestAnimationFrame(tick);
    });
  }
  cancel() {
    this.cancelled = true;
    for (const a of this.anims) a.cancel();
    for (const [t, rej] of this.timers) {
      clearTimeout(t);
      rej(CANCEL);
    }
  }
  cleanup() {
    for (const a of this.anims) if (a.playState === 'finished') a.cancel();
    this.anims = [];
  }
}

// ----------------------------------------------------------------- grid --
// A keyed table renderer: rows keyed by their "<frame>:<row>" id, cells by
// column name. Everything is absolutely positioned so rows and columns can
// be moved with transforms, which makes FLIP transitions straightforward.
class Grid {
  constructor(parent) {
    this.el = h('div', 'grid');
    this.headEl = h('div', 'ghead');
    this.body = h('div', 'gbody');
    this.el.append(this.headEl, this.body);
    parent.appendChild(this.el);
    this.rows = new Map();
    this.heads = new Map();
    this.widths = new Map();
    this.table = null;
    this.L = null;
    this.x = 0;
    this.y = 0;
  }
  moveTo(x, y) {
    this.x = x;
    this.y = y;
    this.el.style.left = x + 'px';
    this.el.style.top = y + 'px';
  }
  layout(t) {
    const x = new Map();
    let acc = 0;
    t.columns.forEach((c, ci) => {
      let w = this.widths.get(c.name);
      if (!w) {
        w = measure(c, t.rows.map((r) => r[ci]));
        this.widths.set(c.name, w);
      }
      x.set(c.name, { x: acc, w, ci, kind: c.kind });
      acc += w;
    });
    return { x, width: acc, height: HEAD + t.rows.length * ROW };
  }
  rowY(i) {
    return i * ROW;
  }
  headCell(c, L) {
    let e = this.heads.get(c.name);
    if (!e) {
      e = h('div', 'gh');
      e.innerHTML = `<span class="nm"></span><span class="kind"></span>`;
      this.headEl.appendChild(e);
      this.heads.set(c.name, e);
    }
    const p = L.x.get(c.name);
    e.className = 'gh ' + c.kind;
    $('.nm', e).textContent = c.name;
    $('.kind', e).textContent = c.kind === 'cat' ? 'cat' : 'f64';
    e.style.width = p.w + 'px';
    e.style.transform = `translateX(${p.x}px)`;
    const old = e._x;
    e._x = p.x;
    return { e, old };
  }
  makeRow(id) {
    const r = h('div', 'grow');
    r.dataset.id = id;
    r.cells = new Map();
    this.body.appendChild(r);
    this.rows.set(id, r);
    return r;
  }
  syncCells(row, t, i, L, onCell) {
    const names = new Set(t.columns.map((c) => c.name));
    for (const [name, cell] of row.cells) {
      if (!names.has(name)) {
        if (onCell) onCell('exit', cell, name);
        else cell.remove();
        row.cells.delete(name);
      }
    }
    t.columns.forEach((c, ci) => {
      let cell = row.cells.get(c.name);
      const fresh = !cell;
      if (fresh) {
        cell = h('div', 'gcell');
        row.appendChild(cell);
        row.cells.set(c.name, cell);
      }
      const p = L.x.get(c.name);
      cell.className = 'gcell ' + c.kind + (!fresh && onCell && cell.classList.contains('hl') ? ' hl' : '');
      cell.textContent = fmt(t.rows[i][ci]);
      cell.style.width = p.w + 'px';
      const old = cell._x;
      cell._x = p.x;
      cell.style.transform = `translateX(${p.x}px)`;
      if (onCell) onCell(fresh ? 'enter' : 'keep', cell, c.name, old, p.x);
    });
  }
  size(L) {
    this.el.style.width = L.width + 'px';
    this.el.style.height = L.height + 'px';
    this.body.style.height = L.height - HEAD + 'px';
  }
  // Snap to a table with no animation.
  render(t) {
    const L = this.layout(t);
    const names = new Set(t.columns.map((c) => c.name));
    for (const [n, e] of this.heads) if (!names.has(n)) (e.remove(), this.heads.delete(n));
    t.columns.forEach((c) => this.headCell(c, L));
    const ids = new Set(t.ids);
    for (const [id, r] of this.rows) if (!ids.has(id)) (r.remove(), this.rows.delete(id));
    t.ids.forEach((id, i) => {
      const r = this.rows.get(id) || this.makeRow(id);
      r.className = 'grow';
      r.style.opacity = '';
      r._y = this.rowY(i);
      r._i = i;
      r.style.transform = `translateY(${r._y}px)`;
      this.syncCells(r, t, i, L);
    });
    this.reorderDom(t);
    // Drop leftovers of exit animations that were cancelled mid-flight.
    const liveRows = new Set(this.rows.values());
    for (const el of [...this.body.children]) if (!liveRows.has(el)) el.remove();
    const liveHeads = new Set(this.heads.values());
    for (const el of [...this.headEl.children]) if (!liveHeads.has(el)) el.remove();
    for (const r of this.rows.values()) {
      const live = new Set(r.cells.values());
      for (const el of [...r.children]) if (!live.has(el)) el.remove();
    }
    this.size(L);
    this.table = t;
    this.L = L;
    return L;
  }
  reorderDom(t) {
    // Keep DOM order = visual order so the zebra striping stays correct.
    t.ids.forEach((id) => this.body.appendChild(this.rows.get(id)));
  }
  clear() {
    this.headEl.innerHTML = '';
    this.body.innerHTML = '';
    this.rows.clear();
    this.heads.clear();
    this.table = null;
  }
  // FLIP transition to a new table (same frame): moved rows glide, removed
  // rows run `exit`, columns slide horizontally or collapse.
  async morph(t, ctx, o = {}) {
    const L = this.layout(t);
    const anims = [];
    const colExit = (e) => {
      const x = e._x;
      anims.push(ctx.anim(e, [
        { transform: `translateX(${x}px) scaleX(1)`, opacity: 1 },
        { transform: `translateX(${x}px) scaleX(.2)`, opacity: 0 },
      ], { duration: 380, fill: 'forwards' }));
      anims.at(-1).finished.then(() => e.remove(), () => {});
    };
    // header
    const names = new Set(t.columns.map((c) => c.name));
    for (const [n, e] of this.heads) {
      if (!names.has(n)) {
        colExit(e);
        this.heads.delete(n);
      }
    }
    t.columns.forEach((c) => {
      const { e, old } = this.headCell(c, L);
      if (old === undefined) {
        anims.push(ctx.anim(e, [{ opacity: 0, transform: `translateX(${e._x}px) translateY(-8px)` }, { opacity: 1, transform: `translateX(${e._x}px)` }], { duration: 420, delay: 200 }));
      } else if (old !== e._x) {
        anims.push(ctx.anim(e, [{ transform: `translateX(${old}px)` }, { transform: `translateX(${e._x}px)` }], { duration: o.colDuration ?? 620, delay: o.colDelay ?? 160 }));
      }
    });
    // rows
    const ids = new Set(t.ids);
    let exitN = 0;
    for (const [id, r] of this.rows) {
      if (ids.has(id)) continue;
      this.rows.delete(id);
      const y = r._y;
      const a = ctx.anim(r, o.exitFrames ? o.exitFrames(y) : [
        { transform: `translateY(${y}px)`, opacity: 1 },
        { transform: `translateY(${y}px) translateX(-28px) scaleY(.7)`, opacity: 0 },
      ], { duration: o.exitDuration ?? 380, delay: (o.exitStagger ?? 0) * exitN++, fill: 'forwards' });
      a.finished.then(() => r.remove(), () => {});
      anims.push(a);
    }
    t.ids.forEach((id, i) => {
      let r = this.rows.get(id);
      const fresh = !r;
      if (fresh) r = this.makeRow(id);
      const oldY = r._y;
      const oldI = r._i;
      r._y = this.rowY(i);
      r._i = i;
      r.style.transform = `translateY(${r._y}px)`;
      this.syncCells(r, t, i, L, (kind, cell, name, ox, nx) => {
        if (kind === 'exit') colExit(cell);
        else if (kind === 'enter' && !fresh) {
          anims.push(ctx.anim(cell, [{ opacity: 0 }, { opacity: 1 }], { duration: 400, delay: 250 }));
        } else if (kind === 'keep' && ox !== undefined && ox !== nx) {
          anims.push(ctx.anim(cell, [{ transform: `translateX(${ox}px)` }, { transform: `translateX(${nx}px)` }], { duration: o.colDuration ?? 620, delay: (o.colDelay ?? 160) + i * 8 }));
        }
      });
      if (fresh) {
        anims.push(ctx.anim(r, [{ opacity: 0, transform: `translateY(${r._y - 8}px)` }, { opacity: 1, transform: `translateY(${r._y}px)` }], { duration: 380, delay: (o.enterDelay ?? 0) + i * (o.enterStagger ?? 22) }));
      } else if (oldY !== r._y) {
        const delay = (o.delay ?? 0) + (o.stagger ?? 0) * (o.staggerBy === 'old' ? oldI : i);
        const lift = o.lift ?? 0;
        const frames = lift
          ? [
              { transform: `translateY(${oldY}px)` },
              { transform: `translateY(${(oldY + r._y) / 2}px) translateX(${oldY < r._y ? lift : -lift}px) scale(1.015)`, offset: 0.5 },
              { transform: `translateY(${r._y}px)` },
            ]
          : [{ transform: `translateY(${oldY}px)` }, { transform: `translateY(${r._y}px)` }];
        r.classList.add('moving');
        const a = ctx.anim(r, frames, { duration: o.duration ?? 560, delay });
        a.finished.then(() => r.classList.remove('moving'), () => {});
        anims.push(a);
      }
    });
    this.size(L);
    this.table = t;
    this.L = L;
    await ctx.all(anims);
    this.reorderDom(t);
  }
  colX(name) {
    const p = this.L && this.L.x.get(name);
    return p ? p : null;
  }
}

// --------------------------------------------------------------- stage --
const stageInner = $('#stage-inner');
const overlay = $('#overlay');
const links = $('#links');
let grid = new Grid(stageInner);

function stageWidth() {
  return stageInner.clientWidth;
}

function resetStage() {
  overlay.innerHTML = '';
  links.innerHTML = '';
  grid.el.style.opacity = '';
  grid.moveTo(0, 0);
  for (const e of grid.heads.values()) e.classList.remove('hl', 'drop', 'keep');
}

function setStageHeight(hgt) {
  stageInner.style.height = Math.max(hgt, 200) + 'px';
}

function prepare(step) {
  resetStage();
  if (step.before) grid.render(step.before);
  setStageHeight(grid.L ? grid.L.height : 0);
}

// Final (non animated) state of a step.
function renderStatic(step) {
  resetStage();
  if (step.op === 'describe') {
    const hgt = describeCards(step, null);
    grid.render(step.after);
    grid.moveTo(0, hgt + 18);
    setStageHeight(hgt + 18 + grid.L.height);
    return;
  }
  grid.render(step.after);
  setStageHeight(grid.L.height);
}

// ---------------------------------------------------------------- scenes --
const scenes = {
  async load(step, ctx) {
    resetStage();
    grid.clear();
    grid.widths.clear();
    const L = grid.render(step.after);
    setStageHeight(L.height);
    const anims = [];
    [...grid.heads.values()].forEach((e, i) => {
      anims.push(ctx.anim(e, [{ opacity: 0, transform: `translateX(${e._x}px) translateY(-10px)` }, { opacity: 1, transform: `translateX(${e._x}px)` }], { duration: 420, delay: i * 50 }));
    });
    step.after.ids.forEach((id, i) => {
      const r = grid.rows.get(id);
      anims.push(ctx.anim(r, [{ opacity: 0, transform: `translateY(${r._y - 14}px)` }, { opacity: 1, transform: `translateY(${r._y}px)` }], { duration: 420, delay: 200 + i * 28 }));
    });
    await ctx.all(anims);
  },

  async filter(step, ctx) {
    prepare(step);
    const m = step.map;
    const t = step.before;
    const hd = grid.heads.get(m.column);
    hd.style.setProperty('--hl', opColor('filter'));
    hd.classList.add('hl');
    const dropped = new Set(m.dropped);
    const scan = [];
    t.ids.forEach((id, i) => {
      const r = grid.rows.get(id);
      const cell = r.cells.get(m.column);
      cell.style.setProperty('--hl', opColor('filter'));
      const tm = setTimeout(() => {
        if (ctx.cancelled) return;
        cell.classList.add(dropped.has(i) ? 'fail' : 'pass', 'hl');
        if (dropped.has(i)) r.classList.add('drop');
      }, (120 + i * 38) / state.speed);
      ctx.timers.push([tm, () => {}]);
      scan.push(ctx.anim(cell, [{ transform: `translateX(${cell._x}px) scale(1)` }, { transform: `translateX(${cell._x}px) scale(1.12)`, offset: 0.4 }, { transform: `translateX(${cell._x}px) scale(1)` }], { duration: 260, delay: 120 + i * 38 }));
    });
    await ctx.all(scan);
    await ctx.wait(420);
    await grid.morph(step.after, ctx, { duration: 560, stagger: 14, delay: 180, exitStagger: 18 });
    hd.classList.remove('hl');
    for (const r of grid.rows.values()) r.cells.get(m.column)?.classList.remove('hl');
  },

  async select(step, ctx) {
    prepare(step);
    const m = step.map;
    const kept = new Set(m.kept);
    for (const [n, e] of grid.heads) e.classList.add(kept.has(n) ? 'keep' : 'drop');
    const anims = [];
    for (const r of grid.rows.values()) {
      for (const [n, c] of r.cells) {
        if (!kept.has(n)) anims.push(ctx.anim(c, [{ opacity: 1 }, { opacity: 0.3 }], { duration: 300, delay: r._i * 10, fill: 'forwards' }));
      }
    }
    await ctx.all(anims);
    await ctx.wait(300);
    await grid.morph(step.after, ctx, { colDuration: 680, colDelay: 60 });
    for (const e of grid.heads.values()) e.classList.remove('keep', 'drop');
  },

  async sort(step, ctx) {
    prepare(step);
    const m = step.map;
    const hd = grid.heads.get(m.column);
    hd.style.setProperty('--hl', opColor('sort'));
    hd.classList.add('hl');
    const arr = h('span', 'arr', m.ascending ? '↑' : '↓');
    hd.appendChild(arr);
    const anims = [];
    for (const r of grid.rows.values()) {
      const c = r.cells.get(m.column);
      c.style.setProperty('--hl', opColor('sort'));
      c.classList.add('hl');
      anims.push(ctx.anim(c, [{ opacity: 0.4 }, { opacity: 1 }], { duration: 300, delay: r._i * 12 }));
    }
    await ctx.all(anims);
    await ctx.wait(250);
    await grid.morph(step.after, ctx, { duration: 900, stagger: 26, lift: 22, easing: EASE });
    await ctx.wait(200);
    arr.remove();
    hd.classList.remove('hl');
    for (const r of grid.rows.values()) r.cells.get(m.column)?.classList.remove('hl');
  },

  async head(step, ctx) {
    prepare(step);
    const n = step.map.kept;
    const cut = h('div', 'cut');
    cut.style.top = HEAD + n * ROW - 1 + 'px';
    cut.style.width = grid.L.width + 12 + 'px';
    cut.innerHTML = `<span>head(${step.map.n})</span>`;
    overlay.appendChild(cut);
    await ctx.all([ctx.anim(cut, [{ transform: 'scaleX(0)' }, { transform: 'scaleX(1)' }], { duration: 500 })]);
    step.before.ids.forEach((id, i) => {
      if (i >= n) grid.rows.get(id).classList.add('dim');
    });
    await ctx.wait(450);
    await grid.morph(step.after, ctx, {
      exitStagger: 14,
      exitFrames: (y) => [{ transform: `translateY(${y}px)`, opacity: 0.28 }, { transform: `translateY(${y + 16}px)`, opacity: 0 }],
    });
    await ctx.all([ctx.anim(cut, [{ opacity: 1 }, { opacity: 0 }], { duration: 300, fill: 'forwards' })]);
    cut.remove();
  },

  async groupby(step, ctx) {
    prepare(step);
    const m = step.map;
    const t = step.before;
    const keyPos = grid.colX(m.key);
    // 1. colour rows by bucket
    m.groups.forEach((g, gi) => {
      g.rows.forEach((pos, k) => {
        const r = grid.rows.get(t.ids[pos]);
        const tm = setTimeout(() => {
          r.style.setProperty('--gc', gColor(gi));
          r.classList.add('grouped');
          const cell = r.cells.get(m.key);
          cell.innerHTML = '';
          const p = h('span', 'pill', fmt(t.rows[pos][keyPos.ci]));
          p.style.setProperty('--pc', gColor(gi));
          cell.appendChild(p);
        }, (pos * 30) / state.speed);
        ctx.timers.push([tm, () => {}]);
      });
    });
    await ctx.wait(t.ids.length * 30 + 450);

    // 2. buckets + tokens flying in
    const W = stageWidth();
    const n = m.groups.length;
    const perRow = Math.min(n, 4);
    const gap = 14;
    const cardW = Math.min(230, (W - gap * (perRow - 1)) / perRow);
    const maxSize = Math.max(...m.groups.map((g) => g.rows.length));
    const aggH = 12 + m.aggs.length * 22;
    const rowsOfCards = Math.ceil(n / perRow);
    const avail = Math.max(260, (grid.L.height - 20) / rowsOfCards);
    const th = Math.max(5, Math.min(18, (avail - 40 - aggH - 12) / maxSize));
    const cardH = 40 + maxSize * th + 12 + aggH;
    const totalW = perRow * cardW + (perRow - 1) * gap;
    const ox = Math.max(0, (W - totalW) / 2);
    const valueCol = m.aggs.find((a) => a.fn !== 'count')?.column;
    const valuePos = valueCol ? grid.colX(valueCol) : keyPos;
    const cards = m.groups.map((g, gi) => {
      const cx = ox + (gi % perRow) * (cardW + gap);
      const cy = Math.floor(gi / perRow) * (cardH + gap);
      const c = h('div', 'bucket');
      c.style.cssText = `left:${cx}px;top:${cy}px;width:${cardW}px;height:${cardH}px;--gc:${gColor(gi)}`;
      c.innerHTML = `<div class="bh"><i></i><span></span><small>${g.rows.length} row${g.rows.length > 1 ? 's' : ''}</small></div><div class="aggs"></div>`;
      $('.bh span', c).textContent = fmt(g.key);
      const aggBox = $('.aggs', c);
      aggBox.style.height = aggH + 'px';
      const vals = m.aggs.map((a) => {
        const line = h('div', 'agg');
        line.innerHTML = `<span></span><b>0</b>`;
        $('span', line).textContent = a.fn === 'count' ? 'count' : `${a.fn}(${a.column})`;
        aggBox.appendChild(line);
        return $('b', line);
      });
      overlay.appendChild(c);
      return { c, cx, cy, vals };
    });
    setStageHeight(Math.max(grid.L.height, rowsOfCards * (cardH + gap)));
    const anims = [ctx.anim(grid.el, [{ opacity: 1 }, { opacity: 0.05 }], { duration: 500, fill: 'forwards' })];
    cards.forEach(({ c }, gi) => anims.push(ctx.anim(c, [{ opacity: 0, transform: 'translateY(10px) scale(.97)' }, { opacity: 1, transform: 'none' }], { duration: 420, delay: gi * 70 })));
    const tokens = [];
    m.groups.forEach((g, gi) => {
      g.rows.forEach((pos, k) => {
        const tk = h('div', 'token', fmt(t.rows[pos][valuePos.ci]));
        tk.style.setProperty('--gc', gColor(gi));
        const from = { x: grid.x + valuePos.x, y: grid.y + HEAD + pos * ROW + 2, w: valuePos.w, hh: ROW - 4 };
        const to = { x: cards[gi].cx + 10, y: cards[gi].cy + 40 + k * th, w: cardW - 20, hh: Math.max(3, th - 2) };
        tk.style.cssText += `left:${to.x}px;top:${to.y}px;width:${to.w}px;height:${to.hh}px;`;
        if (th < 12) tk.style.fontSize = '0px';
        overlay.appendChild(tk);
        tokens.push(tk);
        anims.push(ctx.anim(tk, [
          { left: from.x + 'px', top: from.y + 'px', width: from.w + 'px', height: from.hh + 'px', fontSize: '10.5px', opacity: 0.2 },
          { opacity: 1, offset: 0.15 },
          { left: to.x + 'px', top: to.y + 'px', width: to.w + 'px', height: to.hh + 'px' },
        ], { duration: 820, delay: 250 + pos * 26 }));
      });
    });
    await ctx.all(anims);

    // 3. reduce: numbers count up, tokens squeeze
    const after = step.after;
    const reduce = [];
    cards.forEach(({ vals }, gi) => {
      vals.forEach((b, ai) => {
        const target = after.rows[gi][ai + 1];
        reduce.push(ctx.tween(700, (p) => (b.textContent = fmt(Number.isInteger(target) ? Math.round(target * p) : target * p)), gi * 90 + ai * 60).then(() => (b.textContent = fmt(target))));
      });
    });
    tokens.forEach((tk) => ctx.anim(tk, [{ opacity: 1 }, { opacity: 0.35 }], { duration: 600, fill: 'forwards' }));
    await Promise.all(reduce);
    if (ctx.cancelled) throw CANCEL;
    await ctx.wait(650);

    // 4. buckets collapse into result rows
    grid.el.getAnimations().forEach((a) => a.cancel());
    grid.render(after);
    setStageHeight(grid.L.height);
    const fin = [];
    after.ids.forEach((id, i) => {
      const r = grid.rows.get(id);
      const { cx, cy } = cards[i];
      fin.push(ctx.anim(r, [
        { transform: `translate(${cx - grid.x}px, ${cy - HEAD}px) scale(.9)`, opacity: 0 },
        { opacity: 1, offset: 0.4 },
        { transform: `translateY(${r._y}px)`, opacity: 1 },
      ], { duration: 700, delay: i * 80 }));
    });
    [...overlay.children].forEach((e) => fin.push(ctx.anim(e, [{ opacity: 1 }, { opacity: 0, transform: 'scale(.96)' }], { duration: 420, fill: 'forwards' })));
    await ctx.all(fin);
    overlay.innerHTML = '';
  },

  async join(step, ctx) {
    prepare(step);
    const m = step.map;
    const left = step.before;
    const right = m.right;
    const W = stageWidth();
    const rg = new Grid(overlay);
    rg.render(right);
    const gap = Math.max(70, Math.min(150, W - grid.L.width - rg.L.width));
    rg.moveTo(grid.L.width + gap, 0);
    setStageHeight(Math.max(grid.L.height, rg.L.height));
    const keyL = grid.colX(m.key);
    const keyR = rg.colX(m.key);
    const keys = [...new Set(m.pairs.map(([l]) => left.rows[l][keyL.ci]))];
    const kColor = (v) => gColor(Math.max(0, keys.indexOf(v)));
    const a1 = [ctx.anim(rg.el, [{ opacity: 0, transform: 'translateX(40px)' }, { opacity: 1, transform: 'none' }], { duration: 520 })];
    for (const g of [grid, rg]) {
      const hd = g.heads.get(m.key);
      hd.style.setProperty('--hl', opColor('join'));
      hd.classList.add('hl');
    }
    await ctx.all(a1);

    // colour key cells, draw one curve per matching pair
    const pillify = (g, t, idx, v) => {
      const cell = g.rows.get(t.ids[idx]).cells.get(m.key);
      cell.innerHTML = '';
      const p = h('span', 'pill', fmt(v));
      p.style.setProperty('--pc', kColor(v));
      cell.appendChild(p);
    };
    const hitL = new Set(m.pairs.map((p) => p[0]));
    const hitR = new Set(m.pairs.map((p) => p[1]));
    left.ids.forEach((id, i) => (hitL.has(i) ? pillify(grid, left, i, left.rows[i][keyL.ci]) : grid.rows.get(id).classList.add('dim')));
    right.ids.forEach((id, i) => (hitR.has(i) ? pillify(rg, right, i, right.rows[i][keyR.ci]) : rg.rows.get(id).classList.add('dim')));
    links.setAttribute('width', W);
    links.setAttribute('height', stageInner.clientHeight);
    const x1 = grid.x + grid.L.width + 2;
    const x2 = rg.x - 2;
    const draw = [];
    m.pairs.forEach(([l, r], k) => {
      const y1 = HEAD + l * ROW + ROW / 2;
      const y2 = HEAD + r * ROW + ROW / 2;
      const col = kColor(left.rows[l][keyL.ci]);
      const d = `M${x1},${y1} C${x1 + gap * 0.5},${y1} ${x2 - gap * 0.5},${y2} ${x2},${y2}`;
      const p = svg('path', { d, stroke: col });
      links.appendChild(p);
      const len = p.getTotalLength();
      p.style.strokeDasharray = len;
      p.style.strokeDashoffset = 0;
      draw.push(ctx.anim(p, [{ strokeDashoffset: len }, { strokeDashoffset: 0 }], { duration: 520, delay: k * 45 }));
      const c1 = svg('circle', { cx: x1, cy: y1, r: 3.2, fill: col });
      const c2 = svg('circle', { cx: x2, cy: y2, r: 3.2, fill: col });
      links.append(c1, c2);
      draw.push(ctx.anim(c1, [{ opacity: 0 }, { opacity: 1 }], { duration: 200, delay: k * 45 }));
      draw.push(ctx.anim(c2, [{ opacity: 0 }, { opacity: 1 }], { duration: 200, delay: k * 45 + 480 }));
    });
    await ctx.all(draw);
    await ctx.wait(900);

    // merge: result rows start from their left row, right columns from the right table
    const fade = [...links.children, rg.el].map((e) => ctx.anim(e, [{ opacity: 1 }, { opacity: 0 }], { duration: 380, fill: 'forwards' }));
    const oldLeftY = (l) => l * ROW;
    const rightCols = step.after.columns.slice(left.columns.length);
    const rightSrc = new Map();
    right.columns.forEach((c) => {
      if (c.name === m.key) return;
      const idx = step.after.columns.findIndex((x, i) => i >= left.columns.length && (x.name === c.name || x.name === c.name + '_right'));
      if (idx >= 0) rightSrc.set(step.after.columns[idx].name, rg.colX(c.name).x + rg.x);
    });
    grid.render(step.after);
    setStageHeight(grid.L.height);
    const merge = [];
    step.after.ids.forEach((id, i) => {
      const [l, r] = m.pairs[i];
      const row = grid.rows.get(id);
      merge.push(ctx.anim(row, [{ transform: `translateY(${oldLeftY(l)}px)` }, { transform: `translateY(${row._y}px)` }], { duration: 700, delay: 120 + i * 30 }));
      for (const c of rightCols) {
        const cell = row.cells.get(c.name);
        const fromX = rightSrc.get(c.name);
        if (fromX == null) continue;
        merge.push(ctx.anim(cell, [
          { transform: `translate(${fromX}px, ${(r - l) * ROW}px)`, opacity: 0.2 },
          { transform: `translateX(${cell._x}px)`, opacity: 1 },
        ], { duration: 760, delay: 160 + i * 30 }));
      }
    });
    await ctx.all([...fade, ...merge]);
    links.innerHTML = '';
    overlay.innerHTML = '';
  },

  async describe(step, ctx) {
    prepare(step);
    const a = [ctx.anim(grid.el, [{ opacity: 1 }, { opacity: 0 }], { duration: 380, fill: 'forwards' })];
    await ctx.all(a);
    const hgt = describeCards(step, ctx);
    grid.el.getAnimations().forEach((x) => x.cancel());
    grid.render(step.after);
    grid.moveTo(0, hgt + 18);
    setStageHeight(hgt + 18 + grid.L.height);
    const rows = [];
    [...grid.heads.values()].forEach((e) => rows.push(ctx.anim(e, [{ opacity: 0 }, { opacity: 1 }], { duration: 400, delay: 900 })));
    step.after.ids.forEach((id, i) => {
      const r = grid.rows.get(id);
      rows.push(ctx.anim(r, [{ opacity: 0, transform: `translateY(${r._y - 10}px)` }, { opacity: 1, transform: `translateY(${r._y}px)` }], { duration: 400, delay: 950 + i * 60 }));
    });
    await ctx.all([...rows, ...ctx.anims.filter((x) => x.playState !== 'finished')]);
  },
};

// Stat cards with sparkline, histogram and box plot. Returns their height.
function describeCards(step, ctx) {
  const before = step.before;
  const after = step.after;
  const hist = step.map.hist;
  const cols = after.columns.slice(1);
  const W = stageWidth();
  const n = cols.length;
  const perRow = Math.min(n, 4);
  const gap = 12;
  const cw = (W - gap * (perRow - 1)) / perRow;
  const ch = 208;
  const stat = (name, s) => after.rows[s][after.columns.findIndex((c) => c.name === name)];
  cols.forEach((c, k) => {
    const x = (k % perRow) * (cw + gap);
    const y = Math.floor(k / perRow) * (ch + gap);
    const card = h('div', 'dcard');
    card.style.cssText = `left:${x}px;top:${y}px;width:${cw}px;height:${ch}px;--c:${gColor(k)}`;
    const title = h('h3');
    title.innerHTML = `<span></span><small>n = ${stat(c.name, 0)}</small>`;
    $('span', title).textContent = c.name;
    card.appendChild(title);

    const sw = cw - 24;
    const sh = 74;
    const sp = svg('svg', { class: 'spark', width: sw, height: sh + 22, viewBox: `0 0 ${sw} ${sh + 22}` });
    const hdat = hist[c.name];
    const bins = hdat.counts.length;
    const maxC = Math.max(...hdat.counts, 1);
    const bw = sw / bins;
    const bars = [];
    hdat.counts.forEach((cnt, b) => {
      const bh = (cnt / maxC) * (sh - 22);
      const r = svg('rect', { class: 'bar', x: b * bw + 1, y: sh - bh, width: Math.max(1, bw - 2), height: Math.max(cnt ? 2 : 0, bh), rx: 2 });
      r.style.transformBox = 'fill-box';
      r.style.transformOrigin = 'bottom';
      const lo = hdat.min + ((hdat.max - hdat.min) * b) / bins;
      const hi = hdat.min + ((hdat.max - hdat.min) * (b + 1)) / bins;
      r.dataset.tip = `<code>${c.name}</code> in [${fmt(lo)}, ${fmt(hi)}${b === bins - 1 ? ']' : ')'}<br><b>${cnt}</b> row${cnt === 1 ? '' : 's'}`;
      sp.appendChild(r);
      bars.push(r);
    });
    sp.appendChild(svg('line', { class: 'base', x1: 0, x2: sw, y1: sh + 0.5, y2: sh + 0.5 }));
    // sparkline of the values in view order, drawn over the histogram's top band
    const ci = before.columns.findIndex((x) => x.name === c.name);
    const vals = before.rows.map((r) => r[ci]);
    const lo = hdat.min;
    const span = hdat.max - hdat.min || 1;
    const pts = vals.map((v, i) => [vals.length > 1 ? (i / (vals.length - 1)) * sw : sw / 2, 18 - ((v - lo) / span) * 16]);
    const line = svg('polyline', { class: 'line', points: pts.map((p) => p.join(',')).join(' ') });
    sp.appendChild(line);
    // box plot
    const bx = (v) => ((v - lo) / span) * sw;
    const by = sh + 12;
    const q1 = stat(c.name, 4), md = stat(c.name, 5), q3 = stat(c.name, 6);
    const box = svg('g');
    box.append(
      svg('line', { class: 'whisk', x1: bx(stat(c.name, 3)), x2: bx(stat(c.name, 7)), y1: by, y2: by }),
      svg('rect', { class: 'box', x: bx(q1), y: by - 6, width: Math.max(1, bx(q3) - bx(q1)), height: 12, rx: 2 }),
      svg('line', { class: 'med', x1: bx(md), x2: bx(md), y1: by - 6, y2: by + 6 }),
    );
    box.dataset.tip = `min ${fmt(stat(c.name, 3))} · q1 ${fmt(q1)} · median ${fmt(md)} · q3 ${fmt(q3)} · max ${fmt(stat(c.name, 7))}`;
    sp.appendChild(box);
    card.appendChild(sp);
    const cap = h('div', 'cap');
    cap.innerHTML = `<span>${fmt(hdat.min)}</span><span>${bins} bins</span><span>${fmt(hdat.max)}</span>`;
    card.appendChild(cap);

    const dl = h('dl');
    const shown = [['mean', 1], ['std', 2], ['min', 3], ['max', 7], ['25%', 4], ['75%', 6]];
    const dds = shown.map(([lab, s]) => {
      const dt = h('dt', null, lab);
      const dd = h('dd', null, ctx ? '0' : fmt(stat(c.name, s)));
      dl.append(dt, dd);
      return [dd, stat(c.name, s)];
    });
    card.appendChild(dl);
    overlay.appendChild(card);

    if (ctx) {
      ctx.anim(card, [{ opacity: 0, transform: 'translateY(12px)' }, { opacity: 1, transform: 'none' }], { duration: 460, delay: k * 110 });
      bars.forEach((r, b) => ctx.anim(r, [{ transform: 'scaleY(0)' }, { transform: 'scaleY(1)' }], { duration: 520, delay: 250 + k * 110 + b * 45 }));
      const len = line.getTotalLength ? line.getTotalLength() : 400;
      line.style.strokeDasharray = len;
      ctx.anim(line, [{ strokeDashoffset: len }, { strokeDashoffset: 0 }], { duration: 900, delay: 350 + k * 110, easing: 'ease-in-out' });
      ctx.anim(box, [{ opacity: 0, transform: 'scaleX(.3)' }, { opacity: 1, transform: 'none' }], { duration: 500, delay: 700 + k * 110 });
      dds.forEach(([dd, v], j) => ctx.tween(700, (p) => (dd.textContent = fmt(v * p)), 500 + k * 110 + j * 40).then(() => (dd.textContent = fmt(v))));
    }
  });
  return Math.ceil(n / perRow) * (ch + gap) - gap;
}

// ---------------------------------------------------------- engine panel --
function frameStorage(fid) {
  return state.frames.get(fid);
}

function renderEngine(step, animate) {
  const i = step.index;
  // call chain
  const code = $('#code');
  code.innerHTML = '';
  state.trace.steps.forEach((s, k) => {
    if (!s.cpp) return;
    const ln = h('span', 'ln' + (k < i ? ' past' : k === i ? ' cur' : ''));
    ln.style.setProperty('--c', opColor(s.op));
    const txt = (k === 0 ? '' : '  ') + s.cpp + (k === 0 ? '\ndf' : '');
    ln.innerHTML = txt
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/"([^"]*)"/g, '<span class="s">"$1"</span>')
      .replace(/\b(DataFrame|double|return)\b/g, '<span class="k">$1</span>');
    code.appendChild(ln);
  });
  code.querySelector('.cur')?.scrollIntoView({ block: 'nearest' });

  // stats
  const st = step.stats;
  const materialized = step.storage && step.op !== 'load';
  $('#stats').innerHTML = `
    <div class="stat"><span class="v"><span class="from">${st.rowsIn} → </span>${st.rowsOut}</span><span class="l">rows</span></div>
    <div class="stat"><span class="v"><span class="from">${st.colsIn} → </span>${st.colsOut}</span><span class="l">columns</span></div>
    <div class="stat"><span class="v">${st.micros < 1000 ? st.micros.toFixed(1) + ' µs' : (st.micros / 1000).toFixed(2) + ' ms'}</span><span class="l">${state.source === 'cpp' ? 'C++ binary, -O2' : 'JS port in browser'}</span></div>`;

  // view internals, animated with a real FLIP (measure, mutate, invert, play)
  $('#view-frame').textContent = `→ frame #${step.view.frame}` + (materialized ? '  (new DataFrame)' : step.op === 'load' ? '  (loaded)' : '  (same frame, 0 bytes copied)');
  $('#view-hint').textContent = materialized || step.op === 'load' ? 'owning result' : 'zero-copy view';
  flipStrip($('#col-idx'), step.view.columnIndices.map((c) => ({ key: step.view.frame + 'c' + c, text: c, cls: 'col', tip: frameStorage(step.view.frame)?.columns[c]?.name })), animate);
  flipStrip($('#row-idx'), step.view.rowIndices.map((r) => ({ key: step.view.frame + ':' + r, text: r })), animate);
  $('#row-count').textContent = `size ${step.view.rowIndices.length}`;

  // storage strip
  const fs = frameStorage(step.view.frame);
  const box = $('#storage');
  box.innerHTML = '';
  if (!fs) return;
  const inRows = new Set(step.view.rowIndices);
  const inCols = new Set(step.view.columnIndices);
  fs.columns.forEach((c, ci) => {
    const row = h('div', 'scol' + (inCols.has(ci) ? '' : ' out'));
    const nm = h('div', 'n');
    nm.innerHTML = `<i>${ci}</i> `;
    nm.appendChild(document.createTextNode(c.name));
    const cells = h('div', 'cells');
    const nums = c.data;
    const lo = Math.min(...nums);
    const hi = Math.max(...nums);
    nums.forEach((v, r) => {
      const b = h('b');
      if (c.kind === 'cat') b.style.setProperty('--cc', gColor(v));
      else {
        const p = hi > lo ? (v - lo) / (hi - lo) : 0.5;
        b.style.setProperty('--cc', `color-mix(in srgb, var(--accent) ${Math.round(18 + p * 82)}%, var(--panel-2))`);
      }
      if (!inRows.has(r) || !inCols.has(ci)) b.classList.add('off');
      b.dataset.tip = `<code>${c.name}[${r}]</code> = ${fmt(v)}${c.kind === 'cat' ? ` <span class="t">→ "${c.labels[v]}"</span>` : ''}${inRows.has(r) ? '' : '<br><span class="t">not in this view</span>'}`;
      cells.appendChild(b);
    });
    row.append(nm, cells);
    box.appendChild(row);
    if (c.kind === 'cat') {
      const d = h('div', 'dict');
      d.textContent = 'dict: ' + c.labels.map((l, k) => `${k}=${l}`).join('  ');
      box.appendChild(d);
    }
    if (animate && step.storage) {
      [...cells.children].forEach((b, k) => b.animate([{ transform: 'scaleY(0)' }, { transform: 'none' }], { duration: 300 / state.speed, delay: (ci * 60 + k * 14) / state.speed, fill: 'backwards', easing: EASE }));
    }
  });
  const note = h('div', 'note', `${fs.columns.length} × ${fs.columns[0]?.data.length ?? 0} doubles = ${(fs.columns.length * (fs.columns[0]?.data.length ?? 0) * 8).toLocaleString()} bytes. Bright cells are the ones this view can see.`);
  box.appendChild(note);
}

function flipStrip(el, items, animate) {
  const first = new Map();
  for (const c of el.children) first.set(c.dataset.key, c.getBoundingClientRect());
  const old = new Map([...el.children].map((c) => [c.dataset.key, c]));
  const next = items.map((it) => {
    let c = old.get(it.key);
    if (!c) {
      c = h('span', 'idx ' + (it.cls || ''));
      c.dataset.key = it.key;
    }
    c.textContent = it.text;
    if (it.tip) c.dataset.tip = `<code>${it.tip}</code>`;
    old.delete(it.key);
    return c;
  });
  const leaving = [...old.values()];
  el.replaceChildren(...next);
  if (!animate) return;
  next.forEach((c, i) => {
    const f = first.get(c.dataset.key);
    const l = c.getBoundingClientRect();
    if (!f) {
      c.animate([{ opacity: 0, transform: 'scale(.6)' }, { opacity: 1, transform: 'none' }], { duration: 320 / state.speed, delay: (i * 12) / state.speed, fill: 'backwards', easing: EASE });
      return;
    }
    const dx = f.left - l.left;
    const dy = f.top - l.top;
    if (dx || dy) c.animate([{ transform: `translate(${dx}px, ${dy}px)` }, { transform: 'none' }], { duration: 560 / state.speed, delay: (i * 10) / state.speed, easing: EASE, fill: 'backwards' });
  });
  // ghosts for removed indices
  leaving.forEach((c) => {
    const f = first.get(c.dataset.key);
    const pr = el.getBoundingClientRect();
    const g = c.cloneNode(true);
    g.style.cssText = `position:absolute;left:${f.left - pr.left}px;top:${f.top - pr.top}px;border-color:var(--bad);color:var(--bad)`;
    el.style.position = 'relative';
    el.appendChild(g);
    g.animate([{ opacity: 1 }, { opacity: 0, transform: 'translateY(6px) scale(.7)' }], { duration: 420 / state.speed, easing: EASE, fill: 'forwards' }).finished.then(() => g.remove());
  });
}

// ------------------------------------------------------------ stage head --
function renderStageHead(step) {
  const el = $('#stage-head');
  if (step.error) {
    el.innerHTML = `<span class="badge" style="--c:var(--bad)">${icon(step.op)}error</span><span class="title"></span><span class="desc"></span>`;
    $('.title', el).textContent = step.text;
    $('.desc', el).textContent = step.error;
    return;
  }
  el.innerHTML = `<span class="badge" style="--c:${opColor(step.op)}">${icon(step.op)}${step.op}</span><span class="title"></span><span class="desc"></span>`;
  $('.title', el).textContent = `step ${step.index + 1}/${state.trace.steps.length}`;
  $('.desc', el).textContent = EXPLAIN[step.op] || '';
}

// ---------------------------------------------------------------- chips --
function summary(spec) {
  const a = spec.args;
  switch (spec.op) {
    case 'load': return a[0] || '';
    case 'filter': return (a[0] || '').replace('>=', ' ≥ ').replace('<=', ' ≤ ').replace('!=', ' ≠ ').replace('==', ' = ').replace(/([^ ≥≤≠=])([<>])/, '$1 $2 ');
    case 'select': return (a[0] || '').split(',').join(', ');
    case 'sort': return `${a[0] || ''} ${a[1] === 'desc' ? '↓' : '↑'}`;
    case 'head': return a[0] || '5';
    case 'groupby': return `${a[0] || ''} → ${(a[1] || '').split(',').join(', ')}`;
    case 'join': return `${a[0] || ''} on ${a[1] || ''}`;
    default: return '';
  }
}

function renderChips(enterIndex = -1) {
  const box = $('#chips');
  box.innerHTML = '';
  const specs = parsePipeline(state.pipeline);
  specs.forEach((s, i) => {
    if (i > 0) {
      const ar = document.createElementNS(SVGNS, 'svg');
      ar.setAttribute('viewBox', '0 0 22 12');
      ar.classList.add('arrow');
      if (i <= state.index) ar.classList.add('lit');
      ar.innerHTML = '<path d="M2 6h16m-4-4 4 4-4 4"/>';
      box.appendChild(ar);
    }
    const st = state.trace?.steps[i];
    const chip = h('div', 'chip');
    chip.style.setProperty('--c', opColor(s.op));
    if (st?.error) chip.classList.add('error');
    else if (i < state.index) chip.classList.add('done');
    else if (i === state.index) chip.classList.add('active');
    if (i === enterIndex) chip.classList.add('enter');
    chip.innerHTML = `<span class="ico">${icon(s.op)}</span><span class="op"></span><span class="sum"></span>${i > 0 ? '<span class="x" title="Remove step">×</span>' : ''}<span class="bar"></span>`;
    $('.op', chip).textContent = s.op;
    $('.sum', chip).textContent = summary(s);
    chip.title = 'Click to jump here, double-click to edit';
    chip.addEventListener('click', (e) => {
      if (e.target.classList.contains('x')) {
        removeStep(i);
        return;
      }
      if (i === state.index) openEditor(i, chip);
      else goTo(i, true);
    });
    chip.addEventListener('dblclick', () => openEditor(i, chip));
    box.appendChild(chip);
  });
  const add = h('button', 'add');
  add.innerHTML = '<span style="font-size:15px;line-height:1">+</span> add step';
  add.addEventListener('click', () => openAddMenu(add));
  box.appendChild(add);
}

function setChipProgress(i, ms) {
  const chips = $('#chips').querySelectorAll('.chip');
  const bar = chips[i]?.querySelector('.bar');
  if (bar) bar.animate([{ transform: 'scaleX(0)' }, { transform: 'scaleX(1)' }], { duration: ms / state.speed, easing: 'linear' });
}

// --------------------------------------------------------------- player --
async function goTo(i, animate) {
  if (!state.trace) return;
  i = Math.max(0, Math.min(i, state.trace.steps.length - 1));
  if (state.scene) state.scene.cancel();
  if (state.hold) state.hold.cancel();
  state.hold = null;
  const prev = state.index;
  state.index = i;
  const step = state.trace.steps[i];
  renderChips();
  renderStageHead(step);
  if (step.error) {
    toast(step.error);
    stopPlaying();
    return;
  }
  const doAnim = animate && (i === prev + 1 || (i === 0 && step.op === 'load'));
  if (!doAnim && i !== prev + 1 && animate && i > 0) {
    // jumping: snap to the previous step, then animate this one
    renderStatic(state.trace.steps[i - 1]);
  }
  renderEngine(step, true);
  if (!animate) {
    renderStatic(step);
    return;
  }
  const ctx = new Ctx();
  state.scene = ctx;
  setChipProgress(i, 2600);
  try {
    await scenes[step.op](step, ctx);
    ctx.cleanup();
  } catch (e) {
    if (e !== CANCEL) console.error(e);
    return;
  } finally {
    if (state.scene === ctx) state.scene = null;
  }
  if (state.playing) {
    const hold = new Ctx();
    state.hold = hold;
    try {
      await hold.wait(1100);
    } catch {
      return;
    }
    if (state.playing && state.index === i && !state.scene && state.hold === hold) {
      if (i + 1 < state.trace.steps.length) goTo(i + 1, true);
      else stopPlaying();
    }
  }
}

function play() {
  if (!state.trace) return;
  state.playing = true;
  $('#play').classList.add('playing');
  if (state.scene) return;
  if (state.index >= state.trace.steps.length - 1) goTo(0, true);
  else goTo(state.index + 1, true);
}

function stopPlaying() {
  state.playing = false;
  $('#play').classList.remove('playing');
}

// ---------------------------------------------------------------- loading --
function indexFrames() {
  state.frames = new Map();
  for (const s of state.trace.steps) if (s.storage) state.frames.set(s.storage.frame, s.storage);
}

// Pick one row height for the whole trace so every table fits the stage.
function fitRows() {
  if (!state.trace) return;
  let maxRows = 1;
  for (const s of state.trace.steps) {
    for (const t of [s.before, s.after, s.map?.right]) if (t) maxRows = Math.max(maxRows, t.rows.length);
  }
  const avail = $('#stage').clientHeight - 34;
  ROW = Math.max(17, Math.min(26, Math.floor((avail - HEAD - 6) / maxRows)));
  document.documentElement.style.setProperty('--row', ROW + 'px');
  $('#stage').classList.toggle('dense', ROW < 21);
}

function setTrace(trace, source) {
  state.trace = trace;
  state.source = source;
  state.pipeline = trace.pipeline;
  state.index = -1;
  indexFrames();
  fitRows();
  grid.widths.clear();
  $('#pipe-text').value = state.pipeline.split(' | ').join('\n| ');
  $('#cli').textContent = `./build/DataFrame --trace "${state.pipeline}" --data-dir web/data`;
  const src = $('#source');
  src.className = 'source' + (source === 'js' ? ' js' : '');
  src.innerHTML = source === 'cpp'
    ? '<span class="dot"></span>trace recorded from the C++ binary'
    : '<span class="dot"></span>edited pipeline: running the JS port (verified identical to C++)';
  document.querySelectorAll('#recipes button').forEach((b) => b.classList.toggle('on', state.recipe && b.dataset.id === state.recipe.id && source === 'cpp'));
}

async function loadRecipe(r, autoplay = true) {
  const trace = await fetch(`traces/${r.id}.json`).then((x) => x.json());
  state.recipe = r;
  setTrace(trace, 'cpp');
  renderChips();
  if (autoplay) {
    state.playing = true;
    $('#play').classList.add('playing');
    goTo(0, true);
  } else goTo(0, false);
}

async function loadDataset(ds, autoplay = true) {
  state.dataset = ds;
  document.querySelectorAll('#datasets button').forEach((b) => b.classList.toggle('on', b.dataset.id === ds.id));
  const texts = await Promise.all(ds.files.map((f) => fetch('data/' + f).then((x) => x.text())));
  ds.files.forEach((f, i) => (state.files[f] = texts[i]));
  const box = $('#recipes');
  box.innerHTML = '<span class="lbl">Recipes</span>';
  ds.recipes.forEach((r) => {
    const b = h('button', null, r.title);
    b.dataset.id = r.id;
    b.title = r.blurb;
    b.addEventListener('click', () => loadRecipe(r));
    box.appendChild(b);
  });
  await loadRecipe(ds.recipes[0], autoplay);
}

// Run an edited pipeline. A pipeline identical to a recipe uses the C++ trace.
function runText(text, focusStep) {
  const norm = parsePipeline(text).map((s) => s.text).join(' | ');
  const rec = state.doc.datasets.flatMap((d) => d.recipes).find((r) => r.pipeline === norm);
  if (rec) {
    fetch(`traces/${rec.id}.json`).then((x) => x.json()).then((t) => {
      state.recipe = rec;
      setTrace(t, 'cpp');
      afterRun(focusStep);
    });
    return;
  }
  const trace = runPipeline(norm, state.files);
  setTrace(trace, 'js');
  afterRun(focusStep);
}

function afterRun(focusStep) {
  const last = state.trace.steps.length - 1;
  let target = focusStep ?? 0;
  target = Math.min(target, last);
  const err = state.trace.steps.findIndex((s) => s.error);
  if (err >= 0) target = err;
  renderChips(focusStep ?? -1);
  if (target > 0) {
    state.index = target - 1;
    renderStatic(state.trace.steps[target - 1]);
  }
  stopPlaying();
  goTo(target, true);
}

// ------------------------------------------------------------- editing --
function specToText(op, args) {
  return [op, ...args].join(':');
}

function columnsAt(i) {
  const steps = state.trace.steps;
  const s = steps[i];
  if (s?.before) return s.before.columns;
  for (let k = Math.min(i, steps.length) - 1; k >= 0; k--) if (steps[k].after) return steps[k].after.columns;
  return [];
}

function updateStep(i, text) {
  const specs = parsePipeline(state.pipeline).map((s) => s.text);
  if (text == null) specs.splice(i, 1);
  else specs[i] = text;
  closePopover();
  runText(specs.join(' | '), text == null ? Math.max(0, i - 1) : i);
}

function removeStep(i) {
  updateStep(i, null);
}

function defaultStep(op, cols) {
  const num = cols.filter((c) => c.kind === 'num').map((c) => c.name);
  const cat = cols.filter((c) => c.kind === 'cat').map((c) => c.name);
  const ds = state.dataset;
  switch (op) {
    case 'filter': return num.length ? `filter:${num[num.length - 1]}>0` : `filter:${cat[0]}!=x`;
    case 'select': return `select:${cols.slice(0, 3).map((c) => c.name).join(',')}`;
    case 'sort': return `sort:${num[0] || cols[0].name}:desc`;
    case 'head': return 'head:5';
    case 'groupby': return `groupby:${cat[0] || num[0]}:count${num.length ? `,mean(${num.find((n) => n !== (cat[0] || num[0])) || num[0]})` : ''}`;
    case 'join': {
      // Prefer a file that shares a column with the current table.
      const names = cols.map((c) => c.name);
      const header = (f) => (state.files[f] || '').split('\n')[0].trim().split(',');
      const opts = [...ds.files.filter((f) => f !== ds.file), ds.file];
      for (const f of opts) {
        const key = header(f).find((n) => names.includes(n));
        if (key) return `join:${f}:${key}`;
      }
      return `join:${opts[0]}:${names[0]}`;
    }
    case 'describe': return 'describe';
    default: return op;
  }
}

function openAddMenu(anchor) {
  const pop = $('#popover');
  pop.innerHTML = '<h4>Add a step</h4><div class="menu"></div>';
  const menu = $('.menu', pop);
  for (const op of OPS.slice(1)) {
    const b = h('button');
    b.style.setProperty('--c', opColor(op));
    b.innerHTML = `<span class="ico">${icon(op)}</span><span>${op}</span>`;
    b.addEventListener('click', () => {
      const n = parsePipeline(state.pipeline).length;
      const cols = columnsAt(n);
      const specs = parsePipeline(state.pipeline).map((s) => s.text);
      specs.push(defaultStep(op, cols));
      closePopover();
      runText(specs.join(' | '), n);
    });
    menu.appendChild(b);
  }
  showPopover(anchor);
}

function openEditor(i, anchor) {
  const spec = parsePipeline(state.pipeline)[i];
  const cols = columnsAt(i);
  const pop = $('#popover');
  pop.innerHTML = '';
  const head = h('h4');
  head.innerHTML = `<span class="ico" style="color:${opColor(spec.op)}">${icon(spec.op)}</span>edit ${spec.op}`;
  head.querySelector('svg').style.cssText = 'width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:2';
  pop.appendChild(head);
  const form = h('div');
  pop.appendChild(form);
  const sel = (options, value) => {
    const s = h('select');
    for (const o of options) {
      const op = h('option', null, o.label ?? o);
      op.value = o.value ?? o;
      if (op.value === value) op.selected = true;
      s.appendChild(op);
    }
    return s;
  };
  const lab = (t) => form.appendChild(h('label', null, t));
  const names = cols.map((c) => c.name);
  let build;
  const a = spec.args;
  if (spec.op === 'load') {
    lab('file');
    const f = sel(state.dataset.files, a[0]);
    form.appendChild(f);
    build = () => specToText('load', [f.value]);
  } else if (spec.op === 'filter') {
    let cond = { column: names[0], op: '>', value: '0' };
    const m = /^(.*?)(>=|<=|!=|==|>|<)(.*)$/.exec(a[0] || '');
    if (m) cond = { column: m[1].trim(), op: m[2], value: m[3].trim() };
    lab('column / comparison / value');
    const row = h('div', 'row');
    const c = sel(names, cond.column);
    const o = sel(['>=', '<=', '>', '<', '==', '!='], cond.op);
    const v = h('input');
    v.type = 'text';
    v.value = cond.value;
    row.append(c, o, v);
    form.appendChild(row);
    const hint = h('label', null, '');
    form.appendChild(hint);
    const upd = () => {
      const col = cols.find((x) => x.name === c.value);
      hint.textContent = col?.kind === 'cat' ? 'categorical column: use == or != with a label' : 'numeric column';
    };
    c.addEventListener('change', upd);
    upd();
    build = () => specToText('filter', [`${c.value}${o.value}${v.value}`]);
  } else if (spec.op === 'select') {
    lab('columns to keep (in this order)');
    const box = h('div', 'checks');
    const chosen = (a[0] || '').split(',').map((x) => x.trim());
    const order = [...chosen.filter((n) => names.includes(n)), ...names.filter((n) => !chosen.includes(n))];
    const inputs = order.map((n) => {
      const l = h('label');
      const cb = h('input');
      cb.type = 'checkbox';
      cb.checked = chosen.includes(n);
      cb.value = n;
      l.append(cb, document.createTextNode(n));
      box.appendChild(l);
      return cb;
    });
    form.appendChild(box);
    build = () => specToText('select', [inputs.filter((x) => x.checked).map((x) => x.value).join(',')]);
  } else if (spec.op === 'sort') {
    lab('column / direction');
    const row = h('div', 'row');
    const c = sel(names, a[0]);
    const d = sel([{ value: 'asc', label: 'ascending' }, { value: 'desc', label: 'descending' }], a[1] === 'desc' ? 'desc' : 'asc');
    row.append(c, d);
    form.appendChild(row);
    build = () => specToText('sort', d.value === 'desc' ? [c.value, 'desc'] : [c.value]);
  } else if (spec.op === 'head') {
    lab('rows to keep');
    const n = h('input');
    n.type = 'number';
    n.min = 0;
    n.value = a[0] || 5;
    form.appendChild(n);
    build = () => specToText('head', [String(n.value)]);
  } else if (spec.op === 'groupby') {
    lab('group key');
    const k = sel(names, a[0]);
    form.appendChild(k);
    lab('aggregations');
    const cur = (a[1] || '').split(',').map((x) => x.trim());
    const cnt = h('label');
    const cb = h('input');
    cb.type = 'checkbox';
    cb.checked = cur.includes('count');
    cnt.append(cb, document.createTextNode(' count'));
    cnt.style.cssText = 'display:flex;gap:6px;color:var(--text);font-size:12px';
    form.appendChild(cnt);
    const rows = cols.filter((c) => c.kind === 'num').map((c) => {
      const r = h('div', 'aggrow');
      const have = cur.find((x) => x.endsWith(`(${c.name})`));
      const s = sel(['–', 'sum', 'mean', 'min', 'max'], have ? have.split('(')[0] : '–');
      r.append(h('span', null, c.name), s);
      form.appendChild(r);
      return [c.name, s];
    });
    build = () => {
      const aggs = [];
      if (cb.checked) aggs.push('count');
      for (const [n, s] of rows) if (s.value !== '–' && n !== k.value) aggs.push(`${s.value}(${n})`);
      if (!aggs.length) aggs.push('count');
      return specToText('groupby', [k.value, aggs.join(',')]);
    };
  } else if (spec.op === 'join') {
    lab('right table / key column');
    const row = h('div', 'row');
    const f = sel(state.dataset.files, a[0]);
    const k = sel(names, a[1]);
    row.append(f, k);
    form.appendChild(row);
    build = () => specToText('join', [f.value, k.value]);
  } else {
    form.appendChild(h('label', null, 'describe() has no arguments.'));
    build = () => 'describe';
  }
  const btns = h('div', 'btns');
  if (i > 0) {
    const del = h('button', 'danger', 'Remove');
    del.addEventListener('click', () => removeStep(i));
    btns.appendChild(del);
  }
  const cancel = h('button', null, 'Cancel');
  cancel.addEventListener('click', closePopover);
  const ok = h('button', 'primary', 'Apply');
  ok.addEventListener('click', () => updateStep(i, build()));
  btns.append(cancel, ok);
  pop.appendChild(btns);
  showPopover(anchor);
}

function showPopover(anchor) {
  const pop = $('#popover');
  const r = anchor.getBoundingClientRect();
  pop.classList.add('on');
  const w = pop.offsetWidth;
  pop.style.left = Math.max(8, Math.min(window.innerWidth - w - 8, r.left)) + 'px';
  pop.style.top = r.bottom + 8 + 'px';
  stopPlaying();
}

function closePopover() {
  $('#popover').classList.remove('on');
}

document.addEventListener('mousedown', (e) => {
  const pop = $('#popover');
  if (pop.classList.contains('on') && !pop.contains(e.target) && !e.target.closest('.chip, .add')) closePopover();
});

// -------------------------------------------------------------- tooltip --
const tip = $('#tooltip');
document.addEventListener('mousemove', (e) => {
  const t = e.target.closest?.('[data-tip], .gcell');
  if (!t) return tip.classList.remove('on');
  let html = t.dataset?.tip;
  if (!html && t.classList.contains('gcell')) {
    const row = t.parentElement;
    const [f, r] = row.dataset.id.split(':');
    const name = [...row.cells].find(([, c]) => c === t)?.[0];
    html = `<code>view row ${row._i}</code> <span class="t">→ frame #${f}, row ${r}</span><br><code>${name}</code> = ${t.textContent}`;
  }
  tip.innerHTML = html;
  tip.classList.add('on');
  const x = Math.min(window.innerWidth - tip.offsetWidth - 10, e.clientX + 14);
  tip.style.left = x + 'px';
  tip.style.top = e.clientY + 16 + 'px';
});

let toastTimer;
function toast(msg) {
  const t = $('#toast');
  t.textContent = msg;
  t.classList.add('on');
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => t.classList.remove('on'), 3800);
}

// ------------------------------------------------------------- controls --
$('#play').addEventListener('click', () => (state.playing ? stopPlaying() : play()));
$('#next').addEventListener('click', () => {
  stopPlaying();
  goTo(state.index + 1, true);
});
$('#prev').addEventListener('click', () => {
  stopPlaying();
  goTo(state.index - 1, false);
});
$('#restart').addEventListener('click', () => {
  stopPlaying();
  state.index = -1;
  goTo(0, true);
});
$('#speed').addEventListener('change', (e) => {
  state.speed = Number(e.target.value);
  document.documentElement.style.setProperty('--speed', state.speed);
});
$('#pipe-text').addEventListener('keydown', (e) => {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault();
    runText(e.target.value.replace(/\n/g, ' '), 0);
  }
});
document.addEventListener('keydown', (e) => {
  if (e.target.closest('input, textarea, select')) return;
  if (e.key === ' ') {
    e.preventDefault();
    state.playing ? stopPlaying() : play();
  } else if (e.key === 'ArrowRight') {
    stopPlaying();
    goTo(state.index + 1, true);
  } else if (e.key === 'ArrowLeft') {
    stopPlaying();
    goTo(state.index - 1, false);
  } else if (e.key === 'Home') {
    stopPlaying();
    state.index = -1;
    goTo(0, true);
  } else if (e.key === 'Escape') closePopover();
});

const themeBtn = $('#theme');
function applyTheme(t) {
  document.documentElement.dataset.theme = t;
  try {
    localStorage.setItem('df-theme', t);
  } catch {}
}
themeBtn.addEventListener('click', () => {
  applyTheme(document.documentElement.dataset.theme === 'light' ? 'dark' : 'light');
  if (state.index >= 0) renderEngine(state.trace.steps[state.index], false);
});
let saved = null;
try {
  saved = localStorage.getItem('df-theme');
} catch {}
const params = new URLSearchParams(location.search);
applyTheme(params.get('theme') || saved || (matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark'));

let resizeT;
window.addEventListener('resize', () => {
  clearTimeout(resizeT);
  resizeT = setTimeout(() => {
    fitRows();
    if (state.index >= 0 && !state.scene) renderStatic(state.trace.steps[state.index]);
  }, 150);
});

// ---------------------------------------------------------------- boot --
(async function boot() {
  state.doc = await fetch('recipes.json').then((x) => x.json());
  const nav = $('#datasets');
  state.doc.datasets.forEach((ds) => {
    const b = h('button', null, ds.name.replace(/ \(.*\)/, ''));
    b.dataset.id = ds.id;
    b.title = ds.description;
    b.addEventListener('click', () => {
      stopPlaying();
      loadDataset(ds);
    });
    nav.appendChild(b);
  });
  const want = state.doc.datasets.find((d) => d.id === params.get('dataset')) || state.doc.datasets[0];
  const autoplay = params.get('autoplay') !== '0';
  await loadDataset(want, false);
  const rec = want.recipes.find((r) => r.id === params.get('recipe'));
  if (rec) await loadRecipe(rec, autoplay);
  else if (autoplay) setTimeout(play, 500);
  window.__df = { state, goTo, loadRecipe, runText, play, stopPlaying };
})();
